### ISSUE TITLE
[Bug] [android] plugin crashes app

### ISSUE THREAD

**Issue by razvang10** [silkimen/cordova-plugin-advanced-http#308]
**Describe the bug**
when i try to make a http request i get a fatal exception and the app crashes.
**System info**
 - affected HTTP plugin version: 2.3.1
 - cordova version: 
 - cordova platform version(s): 8.0.0

```js
E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-2
    Process: , PID: 8614
    java.lang.NoSuchMethodError: No virtual method getHttpUrlChecked(Ljava/lang/String;)Lokhttp3/HttpUrl; in class Lokhttp3/internal/Internal; or its super classes (declaration of 'okhttp3.internal.Internal' appears in /data/app/-b1ess1e6Ds9-hrfW7-IU2g==/base.apk)
        at okhttp3.internal.huc.OkHttpURLConnection.buildCall(OkHttpURLConnection.java:373)
        at okhttp3.internal.huc.OkHttpURLConnection.getOutputStream(OkHttpURLConnection.java:260)
        at okhttp3.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:229)
        at okhttp3.internal.huc.OkHttpsURLConnection.getOutputStream(OkHttpsURLConnection.java:26)
        at com.silkimen.http.HttpRequest.openOutput(HttpRequest.java:2599)
        at com.silkimen.http.HttpRequest.send(HttpRequest.java:2904)
        at com.silkimen.cordovahttp.CordovaHttpBase.sendBody(CordovaHttpBase.java:159)
        at com.silkimen.cordovahttp.CordovaHttpBase.run(CordovaHttpBase.java:81)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
D/InputMethodManager: prepareNavigationBarInfo() DecorView@516bbcc[MainActivity]
    getNavigationBarColor() -855310
V/InputMethodManager: Starting input: tba= ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager: startInputInner - Id : 0
I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport: Input channel constructed: fd=160
    Input channel destroyed: fd=155
D/SERVER: Handling local request: http://localhost/64-es2015.js
D/ViewRootImpl@fd679ee[MainActivity]: MSG_RESIZED: frame=[0,0][1080,2400] ci=[0,76][0,126] vi=[0,76][0,126] or=1
D/ViewRootImpl@fd679ee[MainActivity]: Relayout returned: old=[0,0][1080,2400] new=[0,0][1080,2400] result=0x1 surface={true 482400448512} changed=false
D/ScrollView:  onsize change changed 
I/Process: Sending signal. PID: 8614 SIG: 9
Process 8614 terminated.
```

**Comment by razvang10** [comment]
also a thing to take in consideration it happened after i added uk.co.workingedge.phonegap.plugin.launchnavigator....

**Comment by razvang10** [comment]
Solved the problem happened because the two plugins were in conflict over OKHTTP just added the prefference 
 ` <preference name="OKHTTP_VERSION" value="3.10.0" />`
